### ISSUE TITLE
可以共享一下中文的测试集吗？

### ISSUE THREAD

**Issue by lishaojun412** [MingLunHan/CIF-ColDec#1]
你好，你的“IMPROVING END-TO-END CONTEXTUAL SPEECH RECOGNITION WITH FINE-GRAINED CONTEXTUAL KNOWLEDGE SELECTION”这篇工作很受启发，我们也在做相关的工作，希望能复现一下你的方法，注意到你仓库只有英文的数据集，能否共享中文的数据集，感谢，email：lishaojun18@huawei.com

**Comment by MingLunHan** [comment]
The Chinese dataset is an internal dataset of the company and involves legal and copyright issues, so it cannot be shared. Thank you for your understanding and attention.

**Comment by MingLunHan** [comment]
> 你好，你的“IMPROVING END-TO-END CONTEXTUAL SPEECH RECOGNITION WITH FINE-GRAINED CONTEXTUAL KNOWLEDGE SELECTION”这篇工作很受启发，我们也在做相关的工作，希望能复现一下你的方法，注意到你仓库只有英文的数据集，能否共享中文的数据集，感谢，email：[lishaojun18@huawei.com](mailto:lishaojun18@huawei.com)


The Chinese dataset is an internal dataset of the company and involves legal and copyright issues, so it cannot be shared. Thank you for your understanding and attention.
